FROM debian:stable
MAINTAINER dubwoc <scottz@clevar.me>
ENV DEBIAN_FRONTEND noninteractive
ENV LANG en_US.UTF-8
ENV LC_ALL C.UTF-8
ENV LANGUAGE en_US.UTF-8
USER root
RUN apt-get update && apt-get dist-upgrade -y
